In [1]:
import tensorflow as tf
from tensorflow import keras

In [35]:

# GRADED FUNCTION: train_mnist
def train_mnist():
    # Please write your code only where you are indicated.
    # please do not remove # model fitting inline comments.

    # YOUR CODE SHOULD START HERE
    class myCallback(tf.keras.callbacks.Callback):
      def on_epoch_end(self, epoch, logs={}):
        if(logs.get('accuracy')>0.99):
          print("\nReached 99% accuracy so cancelling training!")
          self.model.stop_training = True
    # YOUR CODE SHOULD END HERE

    mnist = tf.keras.datasets.mnist

    (x_train, y_train),(x_test, y_test) = mnist.load_data()
    # YOUR CODE SHOULD START HERE
    x_train = x_train/255
    x_test = x_test/255
    #callback = Callback()
    # YOUR CODE SHOULD END HERE
    model = tf.keras.models.Sequential([
        # YOUR CODE SHOULD START HERE   
                                        tf.keras.layers.Flatten(input_shape=(28, 28)),
                                        tf.keras.layers.Dense(512, activation = tf.nn.relu), 
                                        tf.keras.layers.Dense(10, activation = tf.nn.softmax)
        # YOUR CODE SHOULD END HERE
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    
    # model fitting
    history = model.fit(x_train, y_train, epochs = 10, callbacks = [myCallback()])
    # model fitting
    return history.epoch

In [36]:
train_mnist()

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 13s 223us/sample - loss: 0.2026 - accuracy: 0.9409
Epoch 2/10
60000/60000 [==============================] - 12s 201us/sample - loss: 0.0800 - accuracy: 0.9753
Epoch 3/10
60000/60000 [==============================] - 12s 192us/sample - loss: 0.0526 - accuracy: 0.9838
Epoch 4/10
60000/60000 [==============================] - 11s 179us/sample - loss: 0.0370 - accuracy: 0.9881
Epoch 5/10
59680/60000 [============================>.] - ETA: 0s - loss: 0.0265 - accuracy: 0.9912
Reached 99% accuracy so cancelling training!
60000/60000 [==============================] - 10s 172us/sample - loss: 0.0265 - accuracy: 0.9912


[0, 1, 2, 3, 4]

In [41]:
# GRADED FUNCTION: train_mnist
def train_mnist():
    # Please write your code only where you are indicated.
    # please do not remove # model fitting inline comments.
    class myCallback(tf.keras.callbacks.Callback):
      def on_epoch_end(self, epoch, logs={}):
        if(logs.get('accuracy')>0.99):
          print("\nReached 99% accuracy so cancelling training!")
          self.model.stop_training = True

    # YOUR CODE SHOULD START HERE

    # YOUR CODE SHOULD END HERE
    #callbacks = myCallback()

    mnist = tf.keras.datasets.mnist

    (x_train, y_train),(x_test, y_test) = mnist.load_data()
    # YOUR CODE SHOULD START HERE
    x_train = x_train/255
    x_test = x_test/255

    # YOUR CODE SHOULD END HERE
    model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                        tf.keras.layers.Dense(512, activation = tf.nn.relu),
                                        tf.keras.layers.Dense(10, activation = tf.nn.softmax)])
                                        
        # YOUR CODE SHOULD START HERE
    
        # YOUR CODE SHOULD END HERE

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    
    # model fitting
    history = model.fit(x_train, y_train, epochs = 10, callbacks=[myCallback()]# YOUR CODE SHOULD START HERE
              # YOUR CODE SHOULD END HERE
    )
    # model fitting
    return history.epoch

In [42]:
train_mnist()

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 12s 196us/sample - loss: 0.1999 - accuracy: 0.9413
Epoch 2/10
60000/60000 [==============================] - 11s 176us/sample - loss: 0.0804 - accuracy: 0.9751
Epoch 3/10
60000/60000 [==============================] - 12s 197us/sample - loss: 0.0528 - accuracy: 0.9837
Epoch 4/10
60000/60000 [==============================] - 10s 166us/sample - loss: 0.0364 - accuracy: 0.9882
Epoch 5/10
59968/60000 [============================>.] - ETA: 0s - loss: 0.0259 - accuracy: 0.9920
Reached 99% accuracy so cancelling training!
60000/60000 [==============================] - 9s 154us/sample - loss: 0.0259 - accuracy: 0.9920


[0, 1, 2, 3, 4]

In [7]:

import tensorflow as tf

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy')>0.99):
      print("\nReached 99% accuracy so cancelling training!")
      self.model.stop_training = True

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

callbacks = myCallback()

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10, callbacks=[callbacks])

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 13s 222us/sample - loss: 0.2013 - accuracy: 0.9403
Epoch 2/10
60000/60000 [==============================] - 13s 216us/sample - loss: 0.0810 - accuracy: 0.9750
Epoch 3/10
60000/60000 [==============================] - 13s 211us/sample - loss: 0.0528 - accuracy: 0.9836
Epoch 4/10
60000/60000 [==============================] - 12s 194us/sample - loss: 0.0362 - accuracy: 0.9884
Epoch 5/10
59872/60000 [============================>.] - ETA: 0s - loss: 0.0265 - accuracy: 0.9917
Reached 99% accuracy so cancelling training!
60000/60000 [==============================] - 11s 184us/sample - loss: 0.0265 - accuracy: 0.9917


In [2]:
input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(
2, 3, activation='relu', input_shape=input_shape[1:])(x)
print(y.shape)

(4, 26, 26, 2)


In [6]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9.]])
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [7]:
x = tf.reshape(x, [1, 3, 3, 1])
x

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]], dtype=float32)>

In [8]:
x = tf.constant([[1., 2., 3., 4.],
                 [5., 6., 7., 8.],
                 [9., 10., 11., 12.]])
x = tf.reshape(x, [1, 3, 4, 1])
x

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],

        [[ 5.],
         [ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.],
         [12.]]]], dtype=float32)>